#baseURL='https://skydog23.github.io/simpleHugo/'
#baseURL='http://localhost:1313/simpleHugo/'
languageCode = 'en-us'
title = 'Simplest Hugo Site'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true